class AnimeCrud:
    @staticmethod
    async def add(): ...
    @staticmethod
    async def delete(title: str): ...
    @staticmethod
    async def get_by_title(title): ...
    @staticmethod
    async def get(): ...
    @staticmethod
    async def update(): ...
