version: "3.9"

services:
  api:
    image: compilation-box:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - ./mongo_data:/data/db
